death-signs: true
diamond-ore-notifications: true
death-lightning: true
map-number: 1
kit-map: true
prevent-ally-damage: true
exp-multiplier:
  global: 2.0
  fishing: 2.0
  smelting: 2.0
  looting-per-level: 1.5
  luck-per-level: 1.5
  fortune-per-level: 1.5
roads:
  allow-claims-besides: true
scoreboard:
  sidebar:
    title: "scoreboard_title: '\xa74\xa7lReaper \xa77\xa7l| \xa7fHCF"
    enabled: true
  nametags:
    enabled: true
combatlog:
  enabled: true
  despawn-delay-ticks: 600
conquest:
  point-loss-per-death: 20
  victory-points: 300
  allow-negative-points: true
warzone:
  radius: 800
factions:
  disallowed-faction-names:
  - EOTW
  min-name-characters: 3
  max-name-characters: 16
  max-members: 25
  max-allies: 1
subclaims:
  min-name-characters: 3
  max-name-characters: 16
relation-colours:
  wilderness: DARK_GREEN
  warzone: LIGHT_PURPLE
  teammate: GREEN
  ally: GOLD
  enemy: RED
  road: GOLD
deaths-till-raidable:
  maximum: 6
  millis-between-updates: 45000
  increment-between-updates: 0.1
deathban:
  base-duration-minutes: 120
  respawn-screen-seconds-before-kick: 15
enchantment-limits:
  PROTECTION_ENVIRONMENTAL: 3
  PROTECTION_FIRE: 3
  SILK_TOUCH: 1
  DURABILITY: 3
  PROTECTION_EXPLOSIONS: 3
  LOOT_BONUS_BLOCKS: 3
  PROTECTION_PROJECTILE: 3
  OXYGEN: 3
  WATER_WORKER: 1
  THORNS: 0
  DAMAGE_ALL: 3
  ARROW_KNOCKBACK: 1
  KNOCKBACK: 1
  FIRE_ASPECT: 1
  LOOT_BONUS_MOBS: 3
  LUCK: 3
  LURE: 3
end:
  open: true
  exit: world,0.5,75,0.5,0,0
eotw:
  chat-symbol-prefix: ''
  chat-symbol-suffix: ''
  last-map-cappers: []
potion-limits:
  STRENGTH: 0
  INVISIBILITY: 0
  REGEN: 0
  WEAKNESS: 0
  INSTANT_DAMAGE: 0
  SLOWNESS: 1
  POISON: 1
cbe4f03a-90c5-3499-8991-29d619462ff3:
  Mined:
    Diamond: 2
    Gold: 0
    Emerald: 0
    Coal: 5
    Redstone: 0
    Iron: 0
    Lapis: 0
    Stone: 64
83231d0b-82ca-36e6-82e1-6f79b383e566:
  Mined:
    Diamond: 20
    Gold: 0
    Emerald: 0
    Coal: 0
    Redstone: 0
    Iron: 0
    Lapis: 0
    Stone: 320
cd73c95c-f64e-3e39-8d3f-259469f297c1:
  Mined:
    Diamond: 0
    Gold: 0
    Emerald: 0
    Coal: 0
    Redstone: 0
    Iron: 0
    Lapis: 0
    Stone: 2
3d888af5-1208-3404-b78b-c7333528c5aa:
  Mined:
    Diamond: 3
    Gold: 0
    Emerald: 0
    Coal: 0
    Redstone: 0
    Iron: 0
    Lapis: 0
    Stone: 22
9aabe108-d2a8-312d-8c28-df235aa98c45:
  Mined:
    Diamond: 10
    Gold: 0
    Emerald: 0
    Coal: 0
    Redstone: 0
    Iron: 0
    Lapis: 0
    Stone: 5
7bcf6a76-26e0-33fc-b555-f69fb2a426e6:
  Mined:
    Diamond: 22
    Gold: 0
    Emerald: 0
    Coal: 0
    Redstone: 0
    Iron: 0
    Lapis: 0
    Stone: 0
